project:
  type: website

website:
  title: "Jazz Medical Aesthetics"
  navbar:
    background: light
    search: true
    left:
      - href: index.qmd
        text: Home
      - services.qmd
      - about.qmd
      - contact.qmd
    right:
      - icon: instagram
        href: https://www.instagram.com/jazzmedicalaesthetics/
      - icon: facebook
        href: "#"
      - icon: twitter
        href: "#"
      - text: "Patient Portal"
        href: https://diklw.myaestheticrecord.com/login
  page-footer:
    background: light
    left: "© 2024 Jazz Medical Aesthetics. All rights reserved."
    right: 
      - icon: instagram
        href: https://www.instagram.com/jazzmedicalaesthetics/
      - icon: facebook
        href: "#"
      - icon: twitter
        href: "#"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    smooth-scroll: true
    fontsize: 1.1em
    linestretch: 1.7
    link-external-newwindow: true
    include-in-header:
      - text: |
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">